### ISSUE TITLE
Video Contribution

### ISSUE THREAD

**Issue by amrrs** [PrithivirajDamodaran/ZSIC#1]
Hello @PrithivirajDamodaran 

My contribution to spread the word about your wonderful work - https://www.youtube.com/watch?v=1Xz9P3PkLkw 

Thanks for your work! 

Just sharing it with you!

**Comment by amrrs** [comment]
Also, Please close this issue after you read this!

**Comment by PrithivirajDamodaran** [comment]
Thanks for the kind words - but I don't understand the point of opening an issue for this, You could easily drop a comment to my post in LinkedIn or Twitter where you got the details from.

Engaging with my posts - like/ share / comment would actually get the word out better to your network and extended, also I have noticed you generally don't engage with my content, if you are using my work for your videos the least you could do is engage with my posts 😅

Isn't that a fair request ? Think about it. 😇

**Comment by amrrs** [comment]
> You could easily drop a comment to my post in LinkedIn or Twitter where you got the details from.
I've currently taken a break from engaging on Social Media otherwise I might have dropped a DM 

>Engaging with my posts - like/ share / comment would actually get the word out better to your network and extended
I do that mostly but sometimes I miss 

> I have noticed you generally don't engage with my content
Where I engage is usually based on what I see and my feed shown by Linkedin's algorithm has a lot of influence 

> if you are using my work for your videos the least you could do is engage with my posts 😅
✅ I added your repo to the YT description
✅  I created your name multiple times in the video 
✅  I added a CTA at the end asking people to star the repo and add a shotout 
✅ I myself starred the repo 
But somehow all these don't matter you say "the least" I could do is to engage with your post. 

>I don't understand the point of opening an issue for this
I think that's a mistake. I'm sorry! I'll close it.
